# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='was_published_recently',
            field=models.BooleanField(default=False, verbose_name=polls.models.Question.was_published_recently),
            preserve_default=False,
        ),
    ]
