# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_was_published_recently'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='was_published_recently',
        ),
    ]
